#include "T8ForceNotations.hpp"

std::vector<const char *> get_paths() {
    std::vector<const char *> bmp = {
"resources/none.bmp",

"resources/default/default_1.bmp",
"resources/default/default_2.bmp",
"resources/default/default_3.bmp",
"resources/default/default_4.bmp",
"resources/default_dark/default_dark_1.bmp",
"resources/default_dark/default_dark_2.bmp",
"resources/default_dark/default_dark_3.bmp",
"resources/default_dark/default_dark_4.bmp",
"resources/xbox/xbox_1.bmp",
"resources/xbox/xbox_2.bmp",
"resources/xbox/xbox_3.bmp",
"resources/xbox/xbox_4.bmp",
"resources/xbox_dark/xbox_dark_1.bmp",
"resources/xbox_dark/xbox_dark_2.bmp",
"resources/xbox_dark/xbox_dark_3.bmp",
"resources/xbox_dark/xbox_dark_4.bmp",
"resources/playstation/playstation_1.bmp",
"resources/playstation/playstation_2.bmp",
"resources/playstation/playstation_3.bmp",
"resources/playstation/playstation_4.bmp",
"resources/playstation_dark/playstation_dark_1.bmp",
"resources/playstation_dark/playstation_dark_2.bmp",
"resources/playstation_dark/playstation_dark_3.bmp",
"resources/playstation_dark/playstation_dark_4.bmp",
"resources/1234/1234_1.bmp",
"resources/1234/1234_2.bmp",
"resources/1234/1234_3.bmp",
"resources/1234/1234_4.bmp",
"resources/1234_dark/1234_dark_1.bmp",
"resources/1234_dark/1234_dark_2.bmp",
"resources/1234_dark/1234_dark_3.bmp",
"resources/1234_dark/1234_dark_4.bmp",

"resources/1234_vertical/1234_vertical_1.bmp",
"resources/1234_vertical/1234_vertical_2.bmp",
"resources/1234_vertical/1234_vertical_3.bmp",
"resources/1234_vertical/1234_vertical_4.bmp",
"resources/1234_vertical_dark/1234_vertical_dark_1.bmp",
"resources/1234_vertical_dark/1234_vertical_dark_2.bmp",
"resources/1234_vertical_dark/1234_vertical_dark_3.bmp",
"resources/1234_vertical_dark/1234_vertical_dark_4.bmp",
"resources/playstation_vertical/playstation_vertical_1.bmp",
"resources/playstation_vertical/playstation_vertical_2.bmp",
"resources/playstation_vertical/playstation_vertical_3.bmp",
"resources/playstation_vertical/playstation_vertical_4.bmp",
"resources/playstation_vertical_dark/playstation_vertical_dark_1.bmp",
"resources/playstation_vertical_dark/playstation_vertical_dark_2.bmp",
"resources/playstation_vertical_dark/playstation_vertical_dark_3.bmp",
"resources/playstation_vertical_dark/playstation_vertical_dark_4.bmp",
// "resources/xbox_vertical/xbox_vertical_1.bmp",
// "resources/xbox_vertical/xbox_vertical_2.bmp",
// "resources/xbox_vertical/xbox_vertical_3.bmp",
// "resources/xbox_vertical/xbox_vertical_4.bmp",
// "resources/xbox_vertical_dark/xbox_vertical_dark_1.bmp",
// "resources/xbox_vertical_dark/xbox_vertical_dark_2.bmp",
// "resources/xbox_vertical_dark/xbox_vertical_dark_3.bmp",
// "resources/xbox_vertical_dark/xbox_vertical_dark_4.bmp",



// "resources/xsx/XSX_A.bmp",
// "resources/xsx/XSX_B.bmp",
// "resources/xsx/XSX_COMMON.bmp",
// "resources/xsx/XSX_DIRECTIONAL.bmp",
// "resources/xsx/XSX_DOWN.bmp",
// "resources/xsx/XSX_L.bmp",
// "resources/xsx/XSX_LB.bmp",
// "resources/xsx/XSX_LB_Line.bmp",
// "resources/xsx/XSX_LB_Off.bmp",
// "resources/xsx/XSX_LEFT.bmp",
// "resources/xsx/XSX_LEFT_RIGHT.bmp",
// "resources/xsx/XSX_LS.bmp",
// "resources/xsx/XSX_LT_Line.bmp",
// "resources/xsx/XSX_LT_Off.bmp",
// "resources/xsx/XSX_LT_On.bmp",
// "resources/xsx/XSX_MENU.bmp",
// "resources/xsx/XSX_R.bmp",
// "resources/xsx/XSX_RB.bmp",
// "resources/xsx/XSX_RB_Line.bmp",
// "resources/xsx/XSX_RB_Off.bmp",
// "resources/xsx/XSX_RIGHT.bmp",
// "resources/xsx/XSX_RS.bmp",
// "resources/xsx/XSX_RS_X.bmp",
// "resources/xsx/XSX_RS_Y.bmp",
// "resources/xsx/XSX_RT_Line.bmp",
// "resources/xsx/XSX_RT_Off.bmp",
// "resources/xsx/XSX_RT_On.bmp",
// "resources/xsx/XSX_UP.bmp",
// "resources/xsx/XSX_UP_DOWN.bmp",
// "resources/xsx/XSX_VIEW.bmp",
// "resources/xsx/XSX_X.bmp",
// "resources/xsx/XSX_Y.bmp",

// "resources/ps5/PS5_CIRCLE.bmp",
// "resources/ps5/PS5_CREATE.bmp",
// "resources/ps5/PS5_CROSS.bmp",
// "resources/ps5/PS5_DIRECTIONAL.bmp",
// "resources/ps5/PS5_DOWN.bmp",
// "resources/ps5/PS5_L1_Line.bmp",
// "resources/ps5/PS5_L1_Off.bmp",
// "resources/ps5/PS5_L1_On.bmp",
// "resources/ps5/PS5_L2_Line.bmp",
// "resources/ps5/PS5_L2_Off.bmp",
// "resources/ps5/PS5_L2_On.bmp",
// "resources/ps5/PS5_L3.bmp",
// "resources/ps5/PS5_LEFT.bmp",
// "resources/ps5/PS5_LEFT_RIGHT.bmp",
// "resources/ps5/PS5_LS.bmp",
// "resources/ps5/PS5_OPTIONS.bmp",
// "resources/ps5/PS5_PS5.bmp",
// "resources/ps5/PS5_R1_Line.bmp",
// "resources/ps5/PS5_R1_Off.bmp",
// "resources/ps5/PS5_R1_On.bmp",
// "resources/ps5/PS5_R2_Line.bmp",
// "resources/ps5/PS5_R2_Off.bmp",
// "resources/ps5/PS5_R2_On.bmp",
// "resources/ps5/PS5_R3.bmp",
// "resources/ps5/PS5_RIGHT.bmp",
// "resources/ps5/PS5_RS.bmp",
// "resources/ps5/PS5_RS_X.bmp",
// "resources/ps5/PS5_RS_Y.bmp",
// "resources/ps5/PS5_SQUARE.bmp",
// "resources/ps5/PS5_TOUCH.bmp",
// "resources/ps5/PS5_TRIANGLE.bmp",
// "resources/ps5/PS5_UP.bmp",
// "resources/ps5/PS5_UP_DOWN.bmp",

// "resources/cmd/CMD_01.bmp",
// "resources/cmd/CMD_01_Dark.bmp",
// "resources/cmd/CMD_02.bmp",
// "resources/cmd/CMD_02_Dark.bmp",
// "resources/cmd/CMD_03.bmp",
// "resources/cmd/CMD_03_Dark.bmp",
// "resources/cmd/CMD_04.bmp",
// "resources/cmd/CMD_04_Dark.bmp",
// "resources/cmd/CMD_05.bmp",
// "resources/cmd/CMD_05_Dark.bmp",
// "resources/cmd/CMD_06.bmp",
// "resources/cmd/CMD_06_Dark.bmp",
// "resources/cmd/CMD_07.bmp",
// "resources/cmd/CMD_07_Dark.bmp",
// "resources/cmd/CMD_08.bmp",
// "resources/cmd/CMD_08_Dark.bmp",
// "resources/cmd/CMD_09.bmp",
// "resources/cmd/CMD_09_Dark.bmp",
// "resources/cmd/CMD_10.bmp",
// "resources/cmd/CMD_10_Dark.bmp",
// "resources/cmd/CMD_11.bmp",
// "resources/cmd/CMD_11_Dark.bmp",
// "resources/cmd/CMD_12.bmp",
// "resources/cmd/CMD_12_Dark.bmp",
// "resources/cmd/CMD_13.bmp",
// "resources/cmd/CMD_13_Dark.bmp",
// "resources/cmd/CMD_14.bmp",
// "resources/cmd/CMD_14_Dark.bmp",
// "resources/cmd/CMD_15.bmp",
// "resources/cmd/CMD_15_Dark.bmp",
// "resources/cmd/CMD_16.bmp",
// "resources/cmd/CMD_16_Dark.bmp",
// "resources/cmd/CMD_17.bmp",
// "resources/cmd/CMD_17_Dark.bmp",
// "resources/cmd/CMD_18.bmp",
// "resources/cmd/CMD_18_Dark.bmp",
// "resources/cmd/CMD_35.bmp",
// "resources/cmd/CMD_35_Dark.bmp",
// "resources/cmd/CMD_38.bmp",
// "resources/cmd/CMD_39.bmp",


// "resources/cmn/ASSIST.bmp",
// "resources/cmn/BLANK.bmp",
// "resources/cmn/NOSELECT.bmp",
// "resources/cmn/RAGE.bmp",
// "resources/cmn/ZONE.bmp",

// "resources/CMN_Arts/CMN_Arts_Crouching.bmp",
// "resources/CMN_Arts/CMN_Arts_FloorBreak.bmp",
// "resources/CMN_Arts/CMN_Arts_Gauge.bmp",
// "resources/CMN_Arts/CMN_Arts_Homing.bmp",
// "resources/CMN_Arts/CMN_Arts_PowerCrash.bmp",
// "resources/CMN_Arts/CMN_Arts_Tornade.bmp",
// "resources/CMN_Arts/CMN_Arts_WallBreak.bmp",
// "resources/CMN_Arts/CMN_Arts_Zone.bmp",

};

return bmp;

}

std::vector<const char *> get_cmd() {
    return {"- -","0","1","2","3","4","5","6","7","8","9","Space","Ctrl.",".Ctrl",".Shift","Shift.","Insert","Home","PageUp","Delete","End","PageDown","ArrowUp","ArrowLeft","ArrowRight","ArrowDown","NumPad 0","NumPad 1","NumPad 2","NumPad 3","NumPad 4","NumPad 5","NumPad 6","NumPad 7","NumPad 8","NumPad 9","NumPad /","NumPad *","NumPad -","NumPad +","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","-","^","¥","@","[","]",";",":",",",".","/","\\","=","`",")","$","Ù","*","!","ß","'","Ü","+","Ö","Ä","Ì","È","Ò","À","i","Ñ","Ç","~","¿","<","ظ","ฟ","²","#","o̲","}","|","{","Ж","б","ю","ë","x","ъ","Э","ك","TODO","TODO","TODO","TODO","TODO","TODO","TODO","TODO","TODO","TODO","TODO","_","TODO","TODO","TODO","TODO","\'","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12","tab",".Alt","Alt.","CapsLock","ScrollLock"};
}
